version: '3.8'

services:
  educational-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educational-assistant
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_V1_PREFIX=/api/v1
      - PROJECT_NAME=Educational Content Assistant
      - VERSION=1.0.0
      - OPENAI_MODEL=gpt-4o-mini
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small
      - FAISS_INDEX_PATH=data/faiss_index
      - LESSONS_DIR=data/lessons
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - AGENT_MAX_ITERATIONS=10
      - AGENT_TEMPERATURE=0.7
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - edu-network

networks:
  edu-network:
    driver: bridge

volumes:
  data:
  logs:
  temp: